### ISSUE TITLE
Package install fails 

### ISSUE THREAD

**Issue by ianaverno** [wyozi/atom-color-highlight-gmod#1]
I'll just leave it here:

npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Macbook/.atom/.apm/.apmrc" "--userconfig" "/Users/Macbook/.atom/.apmrc" "install" "/private/var/folders/f2/s0j76lq97l789751p39jm1b00000gn/T/d-115818-11177-17yhlzk/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/atom-color-highlight
npm ERR! 404 
npm ERR! 404 'atom-color-highlight' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'atom-color-highlight-gmod'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/f2/s0j76lq97l789751p39jm1b00000gn/T/apm-install-dir-115818-11177-1289yvx/npm-debug.log

**Comment by looterz** [comment]
Getting the same issue, here's my log.

```
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\loote\\AppData\\Local\\atom\\app-1.0.11\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\loote\\AppData\\Local\\atom\\app-1.0.11\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\loote\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\loote\\.atom\\.apmrc" "install" "C:\\Users\\loote\\AppData\\Local\\Temp\\d-115818-240004-1yjlqwa\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/atom-color-highlight
npm ERR! 404 
npm ERR! 404 'atom-color-highlight' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'atom-color-highlight-gmod'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by wyozi** [comment]
The atom-color-highlight package was renamed to abe33/atom-pigments I believe. The pigments package is pretty buggy for me at the moment (https://github.com/abe33/atom-pigments/issues/81 happens to me for pretty much every color) so I don't know if I'm fixing this until that bug gets fixed.

**Comment by wyozi** [comment]
Install atom-pigments.

abe33/atom-pigments/issues/91
